---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banks
  labels:
    app: banks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banks
  template:
    metadata:
      labels:
        app: banks
    spec:
      containers:
      - name: my-container
        image: abu2thahir3/banks:latest
        ports:
        - containerPort: 8080  # This should match the targetPort in the Service
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-service
  labels:
    app: banks
spec:
  selector:
    app: banks
  type: NodePort
  ports:
  - nodePort: 31010
    port: 8080
    targetPort: 8080  # This should match the containerPort in the Deployment

